# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	# Vagrant virtual environment (box)
	config.vm.box = "ubuntu/trusty64"

	# Update manually
	#if File.exist?("./vagrant/.vagrant") then
		#config.vm.box_check_update = false
	#end

	# The url from where the 'config.vm.box' box will be fetched if it
	# doesn't already exist on the user's system.
	config.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20160209.0.0/providers/virtualbox.box"

	# Create a forwarded port mapping which allows access to a specific port
	# config.vm.network :forwarded_port, guest: 80, host: 8080

	# Create a private network, which allows host-only access to the machine
	# using a specific IP.
	config.vm.network :private_network, ip: "192.168.75.57"

	# Create a public network, which generally matched to bridged network.
	# config.vm.network :public_network

	# If true, then any SSH connections made will enable agent forwarding.
	# Default value: false
	# config.ssh.forward_agent = true
	# config.vm.network :forwarded_port, guest: 22, host: 22022, id: "ssh", disabled: true
	# config.vm.network :forwarded_port, guest: 22, host: 22032, auto_correct: true

	# Share an additional folder to the guest VM.
	# The first argument is the path on the host to the actual folder.
	# The second argument is the path on the guest to mount the folder.
	# The optional third argument is a set of non-required options.
	config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", owner: "vagrant", group: "www-data", mount_options: ["dmode=775,fmode=664"]

	# A script to init out machine's environment
	config.vm.provision :shell, path: "install.sh"
end
