# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "vagrant/multi-machine"
	config.vm.box_url = "https://atlas.hashicorp.com/debian/boxes/jessie64/versions/8.3.0/providers/virtualbox.box"
	config.vm.provision "shell", inline: "echo Hello"
	config.vm.synced_folder ".", "/var/www", create: true
	config.vm.provider "virtualbox" do |v|
                v.memory = 1024
                v.cpus = 2
        end

	config.vm.define "web" do |web|
		web.vm.box = "apache"
        	web.vm.box_url = "https://atlas.hashicorp.com/debian/boxes/jessie64/versions/8.3.0/providers/virtualbox.box"	
		web.vm.network :private_network, ip: "192.168.250.70"
		web.vm.provision "shell", inline: "echo Apache"
		web.vm.synced_folder ".", "/var/www", create: true
	end

	config.vm.define "db" do |db|
		db.vm.box = "mysql"
		db.vm.box_url = "https://atlas.hashicorp.com/debian/boxes/jessie64/versions/8.3.0/providers/virtualbox.box"
		db.vm.network :private_network, ip: "192.168.250.71"
		db.vm.provision "shell", inline: "echo MySQL"
		db.vm.synced_folder ".", "/var/www", create: true
	end

end
